language: cpp
dist: trusty
sudo: required

notifications:
  email: false

git:
  submodules: true
  depth: 3



os: osx
compiler: clang++
env: COMPILER=clang++
before_script:
        - curl -o Vst.zip 'http://www.steinberg.net/sdk_downloads/vstsdk365_12_11_2015_build_67.zip'
        - unzip Vst.zip
        - cp -R 'VST3 SDK' ThirdParty/Vst
script: xcodebuild -project Builds/MacOSX/Camomile.xcodeproj
