language: cpp
dist: trusty
sudo: required

notifications:
  email: false

git:
  submodules: true
  depth: 3

matrix:
  include:
#    - os: linux
#      compiler: gcc
#      before_install:
#        - sudo apt-get -qq update
#        - sudo apt-get install -y libx11-dev
#        - sudo apt-get install -y libxrandr-dev
#        - sudo apt-get install -y libxinerama-dev
#        - sudo apt-get install -y libxcursor-dev
#        - sudo apt-get install -y python-dev libfreetype6-dev
#      script: make -C Builds/LinuxMakefile/ TARGET_ARCH=-m64 CONFIG=Release

    - os: osx
      compiler: clang++
      script:
        - xcodebuild -list -project libpd/libpd.xcodeproj
        - xcodebuild -project libpd/libpd.xcodeproj -target libpd-osx -configuration Release -arch x86_64 ONLY_ACTIVE_ARCH=NO CONFIGURATION_BUILD_DIR="./libs/x86_64" PDINSTANCE=1 PDTHREADS=1
        - xcodebuild -project libpd/libpd.xcodeproj -target libpd-osx -configuration Release -arch i386 ONLY_ACTIVE_ARCH=NO CONFIGURATION_BUILD_DIR="./libs/i386" PDINSTANCE=1 PDTHREADS=1
        - lipo -create -output "./libpd/libs/libpd-osx.a" "./libpd/libs/x86_64/libpd-osx.a" "./libpd/libs/i386/libpd-osx.a"
        - xcodebuild -project Builds/MacOSX/Camomile.xcodeproj -configuration Release
