language: cpp
dist: trusty
sudo: required

notifications:
  email: false

git:
  submodules: true
  depth: 3

matrix:
  include:
    - os: linux
      compiler: gcc
      before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y libx11-dev
        - sudo apt-get install -y libxrandr-dev
        - sudo apt-get install -y libxinerama-dev
        - sudo apt-get install -y libxcursor-dev
        - sudo apt-get install -y python-dev
        - sudo apt-get install -y libfreetype6-dev
        - sudo apt-get install -y libgtk-3-dev
        - sudo apt-get install -y libcurl4-gnutls-dev
        - sudo apt-get install -y alsa
        - sudo apt-get install -y libasound2-dev
        - sudo add-apt-repository -y ppa:webkit-team/ppa
        - sudo apt-get -qq update
        - sudo apt-get install -y libwebkit2gtk-4.0-37 libwebkit2gtk-4.0-dev
      script:
        - cd libpd
        - make UTIL=true EXTRA=true ADDITIONAL_CFLAGS="-DPDINSTANCE=1 -DPDTHREADS=1"
        - cd ..
        - make -C Builds/LinuxMakefile/ TARGET_ARCH=-m64 CONFIG=Release

    - os: osx
      compiler: clang++
      script:
        - xcodebuild -project libpd/libpd.xcodeproj -target libpd-osx -configuration Release -arch x86_64 ONLY_ACTIVE_ARCH=NO CONFIGURATION_BUILD_DIR="./libs/x86_64" OTHER_CFLAGS="-DPD -DUSEAPI_DUMMY -DHAVE_LIBDL -DHAVE_UNISTD_H -DLIBPD_EXTRA -DPDINSTANCE=1 -DPDTHREADS=1" | egrep -A 5 "(error|warning):"
        - xcodebuild -project libpd/libpd.xcodeproj -target libpd-osx -configuration Release -arch i386 ONLY_ACTIVE_ARCH=NO CONFIGURATION_BUILD_DIR="./libs/i386" OTHER_CFLAGS="-DPD -DUSEAPI_DUMMY -DHAVE_LIBDL -DHAVE_UNISTD_H -DLIBPD_EXTRA -DPDINSTANCE=1 -DPDTHREADS=1" | egrep -A 5 "(error|warning):"
        - lipo -create -output "./libpd/libs/libpd-osx.a" "./libpd/libs/x86_64/libpd-osx.a" "./libpd/libs/i386/libpd-osx.a"
        - xcodebuild -project Builds/MacOSX/Camomile.xcodeproj -configuration Release | egrep -A 5 "(error|warning):"
