
environment:
   matrix:
      - CONFIGURATION: Release
        PLATFORM: Win32
        TARGET: Release32
      - CONFIGURATION: Release
        PLATFORM: x64
        TARGET: Release64

os: Visual Studio 2015

install:
    - git submodule update --init --recursive
    - pacman -S msys/make mingw32/mingw-w64-i686-gcc mingw64/mingw-w64-x86_64-gcc

build_script:
    - make -C libpd/ UTIL=true EXTRA=true ADDITIONAL_CFLAGS="-DPDINSTANCE=1 -DPDTHREADS=1"
#- msbuild %APPVEYOR_BUILD_FOLDER%\Builds\VisualStudio2015\Camomile.vcxproj /property:Configuration=%TARGET%

notifications:

  - provider: Email
    on_build_status_changed: false
