
environment:
   matrix:
      - CONFIGURATION: Release
        PLATFORM: x64
        TARGET: Release32
        MSYS2_ARCH: i686
      - CONFIGURATION: Release
        PLATFORM: x64
        TARGET: Release64
        MSYS2_ARCH: x86_64

os: Visual Studio 2015

install:
    - git submodule update --init --recursive
    - C:\msys64\usr\bin\bash -lc "pacman -Syuu --noconfirm"
    - C:\msys64\usr\bin\bash -lc "pacman -S --noconfirm --needed make mingw-w64-i686-gcc mingw-w64-x86_64-gcc"
    - C:\msys64\usr\bin\bash -lc "pacman -S --noconfirm --needed base-devel mingw-w64-i686-toolchain mingw-w64-x86_64-toolchain"
    - C:\msys64\usr\bin\bash -lc "pacman -S --noconfirm --needed mingw-w64-cross-winpthreads-git"
    - C:\msys64\usr\bin\bash -lc "pacman -S --noconfirm mingw-w64-$MSYS2_ARCH-{gcc,gcc-libs,glib2,pkg-config}"'
build_script:
    - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/libpd; PATH=$PATH:C:/mingw64/bin:C:/mingw32/bin; make clobber; make"

#ADDITIONAL_CFLAGS=\"-DPDINSTANCE=1 -DPDTHREADS=1\"

notifications:

  - provider: Email
    on_build_status_changed: false
