
environment:
   matrix:
      - CONFIGURATION: Release
        PLATFORM: Win32
        TARGET: Release32
      - CONFIGURATION: Release
        PLATFORM: x64
        TARGET: Release64

os: Visual Studio 2015

install:
    - git submodule update --init --recursive

before_build:
    - curl -fsS -o Vst.zip 'http://www.steinberg.net/sdk_downloads/vstsdk365_12_11_2015_build_67.zip'
    - 7z e Vst.zip -o%APPVEYOR_BUILD_FOLDER%\ThirdParty\Vst -aoa

build_script: msbuild %APPVEYOR_BUILD_FOLDER%\Builds\VisualStudio2015\Camomile.vcxproj /property:Configuration=%TARGET%

notifications:

  - provider: Email
    on_build_status_changed: false
