
environment:
   matrix:
      - CONFIGURATION: Release
        PLATFORM: x64
        TARGET: Release32
        MSYS2_ARCH: i686
      - CONFIGURATION: Release
        PLATFORM: x64
        TARGET: Release64
        MSYS2_ARCH: x86_64

os: Visual Studio 2015

install:
    - git submodule update --init --recursive
    - C:\msys64\usr\bin\bash -lc "pacman -Syuu --noconfirm"
    - C:\msys64\usr\bin\bash -lc "pacman -S --noconfirm --needed make mingw-w64-i686-gcc mingw-w64-x86_64-gcc"
    - C:\msys64\usr\bin\bash -lc "pacman -S --noconfirm --needed mingw-w64-cross-winpthreads-git"
build_script:
    - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/libpd; MSYS=C:\msys32; MINGW=%MSYS%\mingw32; PATH=\"%MINGW%\bin;%MSYS%\usr\bin\"; make clobber; make csharplib"
#    - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/libpd; ./mingw64_build_csharp.bat

#SET MSYS=C:\msys32
#SET MINGW=%MSYS%\mingw32
#SET PATH=%MINGW%\bin;%MSYS%\usr\bin
#make clobber
#make csharplib
#ADDITIONAL_CFLAGS=\"-DPDINSTANCE=1 -DPDTHREADS=1\"

notifications:

  - provider: Email
    on_build_status_changed: false
