
environment:
   matrix:
      - CONFIGURATION: Release
        PLATFORM: x64
        TARGET: Release32
        MSYS2_ARCH: i686
      - CONFIGURATION: Release
        PLATFORM: x64
        TARGET: Release64
        MSYS2_ARCH: x86_64

os: Visual Studio 2015

install:
    - git submodule update --init --recursive
    - C:\msys64\usr\bin\bash -lc "pacman -Syuu --noconfirm"
    - C:\msys64\usr\bin\bash -lc "pacman -S --noconfirm --needed msys/make msys/mingw-w64-i686-gcc msys/mingw-w64-x86_64-gcc"
    - C:\msys64\usr\bin\bash -lc "pacman -S --noconfirm --needed msys/mingw-w64-cross-winpthreads-git"
build_script:
    - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/libpd; ./mingw64_build_csharp.bat

#ADDITIONAL_CFLAGS=\"-DPDINSTANCE=1 -DPDTHREADS=1\"

notifications:

  - provider: Email
    on_build_status_changed: false
