
environment:
   matrix:
      - PLATFORM: x64
        MINGWARCH: mingw32
      - PLATFORM: x64
        MINGWARCH: mingw64

os: Visual Studio 2015

install:
    - git submodule update --init --recursive
    # MingW
    - C:\msys64\usr\bin\bash -lc "pacman -S --noconfirm --needed mingw-w64-cross-winpthreads-git"
    # CMAKE
    - curl ftp://sourceware.org/pub/pthreads-win32/pthreads-w32-2-9-1-release.zip -o pthreads.zip
    - 7z x -opthreads pthreads.zip  Pre-built.2/dll Pre-built.2/lib Pre-built.2/include
    - set pthreaddir="%APPVEYOR_BUILD_FOLDER%\\pthreads\\Pre-built.2"
    - cd "%pthreaddir%\\include" && copy "*.h" "%APPVEYOR_BUILD_FOLDER%\\src\\"
    - cd "%pthreaddir%\\dll\\%platform%" && copy "pthreadVC2.dll" "%APPVEYOR_BUILD_FOLDER%\\bin\\pthreadVC2.dll"
    - cd "%pthreaddir%\\lib\\%platform%" && copy "pthreadVC2.lib" "%APPVEYOR_BUILD_FOLDER%\\bin\\pthreadVC.lib"
    - cd "%APPVEYOR_BUILD_FOLDER%"
build_script:
    # MingW
    - 'if "%MINGWARCH%"=="mingw32" C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER; ./libpd_mingw32_build.bat"'
    - 'if "%MINGWARCH%"=="mingw64" C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER; ./libpd_mingw64_build.bat"'
    
    - 'if "%MINGWARCH%"=="mingw32" msbuild %APPVEYOR_BUILD_FOLDER%\Instrument\Builds\VisualStudio2015\Camomile.sln /property:Configuration=Release32 /property:Platform=Win32'
    - 'if "%MINGWARCH%"=="mingw32" msbuild %APPVEYOR_BUILD_FOLDER%\Effect\Builds\VisualStudio2015\CamomileFx.sln /property:Configuration=Release32 /property:Platform=Win32'
    - 'if "%MINGWARCH%"=="mingw64" msbuild %APPVEYOR_BUILD_FOLDER%\Instrument\Builds\VisualStudio2015\Camomile.sln /property:Configuration=Release /property:Platform=x64'
    - 'if "%MINGWARCH%"=="mingw64" msbuild %APPVEYOR_BUILD_FOLDER%\Effect\Builds\VisualStudio2015\CamomileFx.sln /property:Configuration=Release /property:Platform=x64'
after_build:
    - cd %APPVEYOR_BUILD_FOLDER%
    - copy %APPVEYOR_BUILD_FOLDER%\Plugins\VST\Camomile.dll %APPVEYOR_BUILD_FOLDER%\Plugins\Camomile.dll
    - copy %APPVEYOR_BUILD_FOLDER%\Plugins\VST3\Camomile.vst3 %APPVEYOR_BUILD_FOLDER%\Plugins\Camomile.vst3
    - copy %APPVEYOR_BUILD_FOLDER%\Plugins\VST\CamomileFx.dll %APPVEYOR_BUILD_FOLDER%\Plugins\CamomileFx.dll
    - copy %APPVEYOR_BUILD_FOLDER%\Plugins\VST3\CamomileFx.vst3 %APPVEYOR_BUILD_FOLDER%\Plugins\CamomileFx.vst3
    - copy %APPVEYOR_BUILD_FOLDER%\Dependencies\libpd\libs\libpd.dll %APPVEYOR_BUILD_FOLDER%\Plugins\libpd.dll
    - copy %APPVEYOR_BUILD_FOLDER%\README.md %APPVEYOR_BUILD_FOLDER%\Plugins\README.md
    - copy %APPVEYOR_BUILD_FOLDER%\ChangeLog.md %APPVEYOR_BUILD_FOLDER%\Plugins\ChangeLog.md
    - copy %APPVEYOR_BUILD_FOLDER%\LICENSE %APPVEYOR_BUILD_FOLDER%\Plugins\LICENSE.txt
    - copy %APPVEYOR_BUILD_FOLDER%\Documentation.pdf %APPVEYOR_BUILD_FOLDER%\Plugins\Documentation.pdf
    - del %APPVEYOR_BUILD_FOLDER%\Plugins\Examples\camomile.sh /Q
    - rmdir %APPVEYOR_BUILD_FOLDER%\Plugins\"Shared Code"\ /S /Q
    - rmdir %APPVEYOR_BUILD_FOLDER%\Plugins\VST\ /S /Q
    - rmdir %APPVEYOR_BUILD_FOLDER%\Plugins\VST3\ /S /Q
    - rename %APPVEYOR_BUILD_FOLDER%\Plugins Camomile
    - 'if "%MINGWARCH%"=="mingw32" 7z a CamomileWindows32.zip %APPVEYOR_BUILD_FOLDER%\Camomile\'
    - 'if "%MINGWARCH%"=="mingw64" 7z a CamomileWindows64.zip %APPVEYOR_BUILD_FOLDER%\Camomile\'

artifacts:
  - path: '*.zip'

deploy:
  provider: GitHub
  auth_token:
    secure: dOi2z1hWIXjc8+TuIZOviwwdVx94sbDnvu/n+70AUcs9tKivL6AoX37oEN2TGigE
  artifact: /.*\.zip/
  on:
    appveyor_repo_tag: true

notifications:

  - provider: Email
    on_build_status_changed: false
