
environment:
   matrix:
      - PLATFORM: x64
        PTHREAD: x64
        COMPILER: "Visual Studio 14 2015 Win64"
        RELEASE: Release
        ZIPFILE: CamomileWindows64
      - PLATFORM: Win32
        PTHREAD: x86
        COMPILER: "Visual Studio 14 2015"
        RELEASE: Release32
        ZIPFILE: CamomileWindows32

os: Visual Studio 2015

install:
    - git submodule update --init --recursive
build_script:
    - cd %APPVEYOR_BUILD_FOLDER%\Dependencies\PthreadWin32
    - msbuild pthread.2015.sln /t:pthread_lib /nologo /p:Configuration=Release /p:Platform=%PLATFORM% /p:TargetName=pthread
    - copy pthread.h %APPVEYOR_BUILD_FOLDER%\Dependencies\pure-data\src\pthread.h
    - copy sched.h %APPVEYOR_BUILD_FOLDER%\Dependencies\pure-data\src\sched.h
    - copy semaphore.h %APPVEYOR_BUILD_FOLDER%\Dependencies\pure-data\src\semaphore.h
    - mkdir %APPVEYOR_BUILD_FOLDER%\Dependencies\build && mkdir %APPVEYOR_BUILD_FOLDER%\Dependencies\build\mscv
    - copy lib\pthread.lib %APPVEYOR_BUILD_FOLDER%\Dependencies\build\mscv\pthread.lib
    - cd %APPVEYOR_BUILD_FOLDER%\Dependencies\LibPd\build\msvc
    - cmake -G "%COMPILER%" -DPD_MULTI=ON -DPD_UTILS=OFF -DMSVC_STATIC_RUNTIME=ON -DMSVC_PTHREAD_LIB="pthread.lib" ../..
    - msbuild libpd.sln /t:libpdstatic /p:Configuration=Release /p:Platform=%PLATFORM%
    - cd %APPVEYOR_BUILD_FOLDER%\Instrument\Builds\VisualStudio2015\
    - msbuild Camomile.sln /p:Configuration=%RELEASE% /p:Platform=%PLATFORM%
    - cd %APPVEYOR_BUILD_FOLDER%\Effect\Builds\VisualStudio2015\
    - msbuild CamomileFx.sln /p:Configuration=%RELEASE% /p:Platform=%PLATFORM%

after_build:
    - cd %APPVEYOR_BUILD_FOLDER%
    - copy %APPVEYOR_BUILD_FOLDER%\Plugins\VST\Camomile.dll %APPVEYOR_BUILD_FOLDER%\Plugins\Camomile.dll
    - copy %APPVEYOR_BUILD_FOLDER%\Plugins\VST3\Camomile.vst3 %APPVEYOR_BUILD_FOLDER%\Plugins\Camomile.vst3
    - copy %APPVEYOR_BUILD_FOLDER%\Plugins\VST\CamomileFx.dll %APPVEYOR_BUILD_FOLDER%\Plugins\CamomileFx.dll
    - copy %APPVEYOR_BUILD_FOLDER%\Plugins\VST3\CamomileFx.vst3 %APPVEYOR_BUILD_FOLDER%\Plugins\CamomileFx.vst3
    - copy %APPVEYOR_BUILD_FOLDER%\README.md %APPVEYOR_BUILD_FOLDER%\Plugins\README.md
    - copy %APPVEYOR_BUILD_FOLDER%\ChangeLog.md %APPVEYOR_BUILD_FOLDER%\Plugins\ChangeLog.md
    - copy %APPVEYOR_BUILD_FOLDER%\LICENSE %APPVEYOR_BUILD_FOLDER%\Plugins\LICENSE.txt
    - copy %APPVEYOR_BUILD_FOLDER%\Documentation.pdf %APPVEYOR_BUILD_FOLDER%\Plugins\Documentation.pdf
    - del %APPVEYOR_BUILD_FOLDER%\Plugins\Examples\camomile.sh /Q
    - rmdir %APPVEYOR_BUILD_FOLDER%\Plugins\"Shared Code"\ /S /Q
    - rmdir %APPVEYOR_BUILD_FOLDER%\Plugins\VST\ /S /Q
    - rmdir %APPVEYOR_BUILD_FOLDER%\Plugins\VST3\ /S /Q
    - rename %APPVEYOR_BUILD_FOLDER%\Plugins Camomile
    - 7z a %ZIPFILE%.zip %APPVEYOR_BUILD_FOLDER%\Camomile\
    - del %APPVEYOR_BUILD_FOLDER%\pthreads.zip

artifacts:
  - path: '*.zip'

deploy:
  provider: GitHub
  auth_token:
    secure: dOi2z1hWIXjc8+TuIZOviwwdVx94sbDnvu/n+70AUcs9tKivL6AoX37oEN2TGigE
  artifact: /.*\.zip/
  on:
    appveyor_repo_tag: true

notifications:

  - provider: Email
    on_build_status_changed: false
