
environment:
   matrix:
      - CONFIGURATION: Release
        PLATFORM: Win32
        TARGET: Release32
        MSYS: msys
      - CONFIGURATION: Release
        PLATFORM: x64
        TARGET: Release64
        MSYS: msys64

os: Visual Studio 2015

install:
    - git submodule update --init --recursive
    #- SET "PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;C:\msys64\mingw32\usr\bin;%PATH%"
    - C:\msys64\mingw32\bin\bash -lc "pacman -Syuu --noconfirm"
    #- bash -lc "pacman -S --noconfirm --needed base"
    - C:\msys64\mingw32\bin\bash -lc "pacman -S --noconfirm --needed make mingw-w64-i686-gcc mingw-w64-x86_64-gcc"
    - C:\msys64\mingw32\bin\bash -lc "pacman -S --noconfirm --needed base-devel mingw-w64-i686-toolchain mingw-w64-x86_64-toolchain"
    - C:\msys64\mingw32\bin\bash -lc "pacman -S --noconfirm --needed mingw-w64-cross-winpthreads-git"

build_script:
    - C:\msys64\mingw32\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/libpd; make clobber; make"

#ADDITIONAL_CFLAGS=\"-DPDINSTANCE=1 -DPDTHREADS=1\"

notifications:

  - provider: Email
    on_build_status_changed: false
