
environment:
   matrix:
      - PLATFORM: x64
        PTHREAD: x64
        COMPILER: "Visual Studio 14 2015 Win64"
        RELEASE: Release
      - PLATFORM: Win32
        PTHREAD: x86
        COMPILER: "Visual Studio 14 2015"
        RELEASE: Release32

os: Visual Studio 2015

install:
    - curl ftp://sourceware.org/pub/pthreads-win32/pthreads-w32-2-9-1-release.zip -o pthreads.zip
    - 7z x -opthreads pthreads.zip  Pre-built.2/dll Pre-built.2/lib Pre-built.2/include
    - mkdir %APPVEYOR_BUILD_FOLDER%\Dependencies\LibPd\build
    - mkdir %APPVEYOR_BUILD_FOLDER%\Dependencies\LibPd\build\msvc
    - for %APPVEYOR_BUILD_FOLDER%\pthreads\Pre-built.2\include %%f in (*.xml) do copy %%f %APPVEYOR_BUILD_FOLDER%\Dependencies\LibPd\pure-data\src
    - copy %APPVEYOR_BUILD_FOLDER%\pthreads\Pre-built.2\lib\%PTHREAD%\pthreadVC2.lib %APPVEYOR_BUILD_FOLDER%\Dependencies\LibPd\build\msv\pthreadVC.lib"
build_script:
    - cd %APPVEYOR_BUILD_FOLDER%\Dependencies\LibPd\build\msvc
    - cmake -G "%COMPILER%" -DPD_MULTI=ON -DPD_UTILS=OFF ../..
    - msbuild libpd.sln /t:libpdstatic /p:Configuration=%RELEASE% /p:Platform=%PLATFORM%
    - cd %APPVEYOR_BUILD_FOLDER%\Instrument\Builds\VisualStudio2015\
    #- msbuild Camomile.sln /p:Configuration=%RELEASE% /p:Platform=%PLATFORM%
    - cd %APPVEYOR_BUILD_FOLDER%\Effect\Builds\VisualStudio2015\
    #- msbuild CamomileFx.sln /p:Configuration=%RELEASE% /p:Platform=%PLATFORM%
after_build:
    - cd %APPVEYOR_BUILD_FOLDER%
    - copy %APPVEYOR_BUILD_FOLDER%\Plugins\VST\Camomile.dll %APPVEYOR_BUILD_FOLDER%\Plugins\Camomile.dll
    - copy %APPVEYOR_BUILD_FOLDER%\Plugins\VST3\Camomile.vst3 %APPVEYOR_BUILD_FOLDER%\Plugins\Camomile.vst3
    - copy %APPVEYOR_BUILD_FOLDER%\Plugins\VST\CamomileFx.dll %APPVEYOR_BUILD_FOLDER%\Plugins\CamomileFx.dll
    - copy %APPVEYOR_BUILD_FOLDER%\Plugins\VST3\CamomileFx.vst3 %APPVEYOR_BUILD_FOLDER%\Plugins\CamomileFx.vst3
    - copy %APPVEYOR_BUILD_FOLDER%\README.md %APPVEYOR_BUILD_FOLDER%\Plugins\README.md
    - copy %APPVEYOR_BUILD_FOLDER%\ChangeLog.md %APPVEYOR_BUILD_FOLDER%\Plugins\ChangeLog.md
    - copy %APPVEYOR_BUILD_FOLDER%\LICENSE %APPVEYOR_BUILD_FOLDER%\Plugins\LICENSE.txt
    - copy %APPVEYOR_BUILD_FOLDER%\Documentation.pdf %APPVEYOR_BUILD_FOLDER%\Plugins\Documentation.pdf
    - del %APPVEYOR_BUILD_FOLDER%\Plugins\Examples\camomile.sh /Q
    - rmdir %APPVEYOR_BUILD_FOLDER%\Plugins\"Shared Code"\ /S /Q
    - rmdir %APPVEYOR_BUILD_FOLDER%\Plugins\VST\ /S /Q
    - rmdir %APPVEYOR_BUILD_FOLDER%\Plugins\VST3\ /S /Q
    - rename %APPVEYOR_BUILD_FOLDER%\Plugins Camomile
    - 'if "%MINGWARCH%"=="mingw32" 7z a CamomileWindows32.zip %APPVEYOR_BUILD_FOLDER%\Camomile\'
    - 'if "%MINGWARCH%"=="mingw64" 7z a CamomileWindows64.zip %APPVEYOR_BUILD_FOLDER%\Camomile\'

artifacts:
  - path: '*.zip'

deploy:
  provider: GitHub
  auth_token:
    secure: dOi2z1hWIXjc8+TuIZOviwwdVx94sbDnvu/n+70AUcs9tKivL6AoX37oEN2TGigE
  artifact: /.*\.zip/
  on:
    appveyor_repo_tag: true

notifications:

  - provider: Email
    on_build_status_changed: false
