
environment:
   matrix:
      - PLATFORM: x64

os: Visual Studio 2015

install:
    - git submodule update --init --recursive
    - C:\msys64\usr\bin\bash -lc "pacman -Syuu --noconfirm"
    - C:\msys64\usr\bin\bash -lc "pacman -S --noconfirm --needed make mingw-w64-i686-gcc mingw-w64-x86_64-gcc"
    - C:\msys64\usr\bin\bash -lc "pacman -S --noconfirm --needed mingw-w64-cross-winpthreads-git"
build_script:
    - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER; ./libpd_mingw64_build.bat"
    - msbuild %APPVEYOR_BUILD_FOLDER%\Builds\VisualStudio2015\Camomile.sln /property:Configuration=Release /property:Platform=x64
    - msbuild %APPVEYOR_BUILD_FOLDER%\Builds\VisualStudio2015\Camomile.sln /property:Configuration=ReleaseFx /property:Platform=x64
after_build:
    - cd %APPVEYOR_BUILD_FOLDER%
    - copy %APPVEYOR_BUILD_FOLDER%\Plugins\Camomile\VST\Camomile.dll %APPVEYOR_BUILD_FOLDER%\Plugins\Camomile\Camomile.dll
    - copy %APPVEYOR_BUILD_FOLDER%\Plugins\Camomile\VST3\Camomile.vst3 %APPVEYOR_BUILD_FOLDER%\Plugins\Camomile\Camomile.vst3
    - copy %APPVEYOR_BUILD_FOLDER%\Plugins\Camomile\VST\CamomileFx.dll %APPVEYOR_BUILD_FOLDER%\Plugins\Camomile\CamomileFx.dll
    - copy %APPVEYOR_BUILD_FOLDER%\Plugins\Camomile\VST3\CamomileFx.vst3 %APPVEYOR_BUILD_FOLDER%\Plugins\Camomile\CamomileFx.vst3
    - copy %APPVEYOR_BUILD_FOLDER%\README.md %APPVEYOR_BUILD_FOLDER%\Plugins\README.md
    - copy %APPVEYOR_BUILD_FOLDER%\LICENSE %APPVEYOR_BUILD_FOLDER%\Plugins\LICENSE.txt
    - rmdir %APPVEYOR_BUILD_FOLDER%\Plugins\Camomile\"Shared Code"\ /S /Q
    - rmdir %APPVEYOR_BUILD_FOLDER%\Plugins\Camomile\VST\ /S /Q
    - rmdir %APPVEYOR_BUILD_FOLDER%\Plugins\Camomile\VST3\ /S /Q
    - rename %APPVEYOR_BUILD_FOLDER%\Plugins Camomile
    - 7z a CamomileWindows.zip %APPVEYOR_BUILD_FOLDER%\Camomile\

artifacts:
  - path: '*.zip'

deploy:
  provider: GitHub
  auth_token:
    secure: dOi2z1hWIXjc8+TuIZOviwwdVx94sbDnvu/n+70AUcs9tKivL6AoX37oEN2TGigE
  artifact: /.*\.zip/
  on:
    appveyor_repo_tag: true

notifications:

  - provider: Email
    on_build_status_changed: false
