
environment:
   matrix:
      - CONFIGURATION: Release
        PLATFORM: Win32
        TARGET: Release32
        MSYS: msys
      - CONFIGURATION: Release
        PLATFORM: x64
        TARGET: Release64
        MSYS: msys64

os: Visual Studio 2015

install:
    - git submodule update --init --recursive
    - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S msys/make mingw32/mingw-w64-i686-gcc mingw64/mingw-w64-x86_64-gcc"
    - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S msys/mingw-w64-cross-winpthreads-git"

build_script:
    - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER; make -C libpd UTIL=true EXTRA=true"'

#ADDITIONAL_CFLAGS=\"-DPDINSTANCE=1 -DPDTHREADS=1\"

notifications:

  - provider: Email
    on_build_status_changed: false
