
environment:
   matrix:
      - CONFIGURATION: Release
        PLATFORM: x64
        TARGET: Release32
        MSYS2_ARCH: i686
      - CONFIGURATION: Release
        PLATFORM: x64
        TARGET: Release64
        MSYS2_ARCH: x86_64

os: Visual Studio 2015

install:
    - git submodule update --init --recursive
    - C:\msys64\usr\bin\bash -lc "pacman -Syuu --noconfirm"
    - C:\msys64\usr\bin\bash -lc "pacman -S --noconfirm --needed make mingw-w64-i686-gcc mingw-w64-x86_64-gcc"
    - C:\msys64\usr\bin\bash -lc "pacman -S --noconfirm --needed mingw-w64-cross-winpthreads-git"
build_script:
    - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/libpd; MSYS=:/msys64; MINGW=:$MSYS/mingw64; PATH=$MINGW/bin;$MSYS/usr/bin; make clobber; make csharplib"

# MSYS=:/msys64; MINGW=:$MSYS/mingw64; PATH=$MINGW/bin;$MSYS/usr/bin
# MSYS=C:/\msys64 PATH=$PATH:/mingw64/bin:/mingw32/bin
#ADDITIONAL_CFLAGS=\"-DPDINSTANCE=1 -DPDTHREADS=1\"

notifications:

  - provider: Email
    on_build_status_changed: false
