
environment:
   matrix:
      - PLATFORM: x64

os: Visual Studio 2015

install:
    - git submodule update --init --recursive
    - C:\msys64\usr\bin\bash -lc "pacman -Syuu --noconfirm"
    - C:\msys64\usr\bin\bash -lc "pacman -S --noconfirm --needed make mingw-w64-i686-gcc mingw-w64-x86_64-gcc"
    - C:\msys64\usr\bin\bash -lc "pacman -S --noconfirm --needed mingw-w64-cross-winpthreads-git"
build_script:
    - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER; ./libpd_mingw64_build.bat"
    - msbuild %APPVEYOR_BUILD_FOLDER%\Builds\VisualStudio2015\Camomile.sln /property:Configuration=Release /property:Platform=x64

notifications:

  - provider: Email
    on_build_status_changed: false
